services:
  - type: web
    name: facial-led-app
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: python3.11 -m gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
    plan: starter
    healthCheckPath: /
    autoDeploy: true 