services:
  - type: web
    name: facial-led-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: 1
    plan: starter
    healthCheckPath: /
    autoDeploy: true 