services:
  - type: web
    name: facial-led-app
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements_render.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
    plan: starter
    healthCheckPath: /
    autoDeploy: true 